---
- name: Configure Netdata
  hosts: all
  vars_files:
    - "../vars/main.yml"
  become: true
  become_method: sudo

  tasks:
  - template:
      src: ../templates/netdata.conf.j2
      dest: /etc/netdata/netdata.conf
      owner: root
      group: root
      mode: u=wrx,g=rx,o=r,+x
    notify: Restart Netdata
    become: true
  
  handlers:
  - name: Restart Netdata
    service:
      name: netdata
      state: restarted