---
- name: Configure Netdata with template
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/netdata.conf.j2"
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: '0755'
  become: true
  notify: Restart Netdata
