---
- name: Download the installation script
  ansible.builtin.get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: ~/kickstart.sh
    mode: +x

- name: Install Netdata
  ansible.builtin.command: ~/kickstart.sh --dont-wait
  changed_when: true

- name: Cleanup installation script
  ansible.builtin.file:
    path: ~/kickstart.sh
    state: absent
