---
- name: Install Netdata
  hosts: all
  vars_files:
    - "../vars/main.yml"

  tasks:
  - name: Download the installation script
    get_url:
      url: https://my-netdata.io/kickstart.sh
      dest: ~/kickstart.sh
      mode: +x
    tags: install

  - name: Install Netdata
    command: ~/kickstart.sh --dont-wait
    tags: install

  - name: Cleanup installation script
    file:
      path: ~/kickstart.sh
      state: absent
    tags: install