---
- name: claim the node to Netdata Cloud
  hosts: all
  vars_files:
    - "../../vars/netdata.yaml"
    - "../../vars/conf.yaml"
  become: true

  tasks:

  - name: claim to Netdata Cloud
    when: netdata_reclaim == false
    block: 

    - name: Claim to Netdata Cloud if not already
      shell:
        cmd: netdata-claim.sh -token={{ netdata_claim_token }} -rooms={{ netdata_claim_rooms }} -url={{ netdata_claim_url }}
        creates: /var/lib/netdata/cloud.d/claimed_id
      become: yes

  - name: re-claim a node to Netdata Cloud
    when: netdata_reclaim == true
    block:

    - name: Ensure `uuidgen` is installed
      stat:
        path: /usr/bin/uuidgen
      register: uuidgen_result

    - name: fail if `uuidgen` is not installed
      fail:
        msg: The system needs `uuidgen` installed to enable re-claiming.
      when: uuidgen_result.stat.exists == false

    - name: reclaim the node with `-id=`
      shell: netdata-claim.sh -token={{ netdata_claim_token }} -rooms={{ netdata_claim_rooms }} -url={{ netdata_claim_url }} -id=$(uuidgen)
      when: uuidgen_result.stat.exists == true
      notify: Restart Netdata
      become: yes

  handlers:
  - name: Restart Netdata
    service:
      name: netdata
      state: restarted
